version: '3.5'

services:

  sample-app:
    container_name: sample-app
    build:
      context: //.
      dockerfile: //dockerfiles/dev/Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development